# Generated by Django 5.2.6 on 2025-10-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(help_text='نام هنرمند در زمان آپلود', max_length=255)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('album_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان آلبوم')),
                ('release_type', models.CharField(choices=[('single', 'تک\u200cآهنگ'), ('album', 'آلبوم'), ('ep', 'EP')], default='single', max_length=20)),
                ('featured_artists', models.CharField(blank=True, help_text='هنرمندان همکار (Feat)', max_length=500, null=True)),
                ('audio_file', models.FileField(help_text='فایل صوتی (WAV/FLAC)', upload_to='tracks/audio/%Y/%m/')),
                ('cover_art', models.ImageField(help_text='کاور آرت (حداقل 3000x3000)', upload_to='tracks/covers/%Y/%m/')),
                ('language', models.CharField(choices=[('persian', 'فارسی'), ('english', 'انگلیسی'), ('arabic', 'عربی'), ('turkish', 'ترکی'), ('instrumental', 'بی\u200cکلام')], default='persian', max_length=20)),
                ('primary_genre', models.CharField(max_length=100, verbose_name='ژانر اصلی')),
                ('secondary_genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='ژانر فرعی')),
                ('composer', models.CharField(blank=True, max_length=255, null=True, verbose_name='آهنگساز')),
                ('lyricist', models.CharField(blank=True, max_length=255, null=True, verbose_name='شاعر')),
                ('arranger', models.CharField(blank=True, max_length=255, null=True, verbose_name='تنظیم\u200cکننده')),
                ('is_explicit', models.BooleanField(default=False, verbose_name='محتوای صریح')),
                ('is_instrumental', models.BooleanField(default=False, verbose_name='بی\u200cکلام')),
                ('is_cover', models.BooleanField(default=False, verbose_name='بازخوانی')),
                ('release_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('previously_released', models.BooleanField(default=False, verbose_name='قبلاً منتشر شده')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='لیبل موسیقی')),
                ('isrc_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد ISRC')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('published', 'منتشر شده')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای مدیر')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد')),
                ('platforms', models.JSONField(default=list, help_text='لیست پلتفرم\u200cهای انتخاب شده')),
                ('shazam_enabled', models.BooleanField(default=False)),
                ('store_maximizer_enabled', models.BooleanField(default=False)),
                ('youtube_content_id_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ترک',
                'verbose_name_plural': 'ترک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
