# Generated by Django 5.2.6 on 2025-10-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('transfer_date', models.CharField(max_length=20, verbose_name='تاریخ واریز')),
                ('transfer_time', models.CharField(max_length=10, verbose_name='ساعت واریز')),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه پیگیری')),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True, verbose_name='4 رقم آخر کارت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/', verbose_name='تصویر رسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('card_holder_name', models.CharField(max_length=255, verbose_name='نام دارنده کارت')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
            },
        ),
    ]
