# Generated by Django 4.2.7 on 2025-10-01 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('melli', 'ملی'), ('mellat', 'ملت'), ('saderat', 'صادرات'), ('tejarat', 'تجارت'), ('parsian', 'پارسیان'), ('saman', 'سامان'), ('pasargad', 'پاسارگاد'), ('sina', 'سینا'), ('postbank', 'پست بانک'), ('other', 'سایر')], max_length=20, verbose_name='بانک')),
                ('card_number', models.CharField(help_text='شماره 16 رقمی کارت', max_length=19, verbose_name='شماره کارت')),
                ('card_holder_name', models.CharField(max_length=100, verbose_name='نام صاحب کارت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی برای این کارت', null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کارت بانکی',
                'verbose_name_plural': 'کارت\u200cهای بانکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tracking_code',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='فایل رسید'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پیگیری'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کاربر'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات ادمین'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_four_digits',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='چهار رقم آخر کارت مبدا'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انتقال'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transfer_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت انتقال'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام روش پرداخت'),
        ),
    ]
