# Generated by Django 5.2.6 on 2025-10-01 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام طرح')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('price_irr', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('duration_days', models.IntegerField(default=365, verbose_name='مدت (روز)')),
                ('max_tracks', models.IntegerField(blank=True, null=True, verbose_name='حداکثر تعداد ترک (null = نامحدود)')),
                ('has_pre_save', models.BooleanField(default=False)),
                ('has_content_id', models.BooleanField(default=False)),
                ('has_splits', models.BooleanField(default=False)),
                ('has_analytics', models.BooleanField(default=True)),
                ('has_shazam', models.BooleanField(default=False)),
                ('has_store_maximizer', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طرح اشتراک',
                'verbose_name_plural': 'طرح\u200cهای اشتراک',
                'ordering': ['price_irr'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='payments.payment')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
