# Generated by Django 5.2.6 on 2025-10-01 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'فصلی'), ('yearly', 'سالانه')], max_length=20, verbose_name='نوع گزارش')),
                ('period_start', models.DateField(verbose_name='شروع دوره')),
                ('period_end', models.DateField(verbose_name='پایان دوره')),
                ('total_streams', models.PositiveIntegerField(default=0, verbose_name='مجموع پخش\u200cها')),
                ('total_unique_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان منحصر')),
                ('total_playlist_saves', models.PositiveIntegerField(default=0, verbose_name='مجموع ذخیره در پلی\u200cلیست')),
                ('detailed_data', models.JSONField(default=dict, verbose_name='جزئیات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش تحلیلی',
                'verbose_name_plural': 'گزارش\u200cهای تحلیلی',
            },
        ),
        migrations.CreateModel(
            name='TrackAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_streams', models.PositiveIntegerField(default=0, verbose_name='مجموع پخش\u200cها')),
                ('unique_listeners', models.PositiveIntegerField(default=0, verbose_name='شنوندگان منحصر')),
                ('playlist_saves', models.PositiveIntegerField(default=0, verbose_name='ذخیره در پلی\u200cلیست')),
                ('average_listen_duration', models.DurationField(blank=True, null=True, verbose_name='میانگین زمان پخش')),
                ('spotify_streams', models.PositiveIntegerField(default=0, verbose_name='پخش\u200cهای Spotify')),
                ('apple_music_streams', models.PositiveIntegerField(default=0, verbose_name='پخش\u200cهای Apple Music')),
                ('youtube_music_streams', models.PositiveIntegerField(default=0, verbose_name='پخش\u200cهای YouTube Music')),
                ('amazon_music_streams', models.PositiveIntegerField(default=0, verbose_name='پخش\u200cهای Amazon Music')),
                ('other_platforms_streams', models.PositiveIntegerField(default=0, verbose_name='پخش\u200cهای سایر پلتفرم\u200cها')),
                ('iran_listeners', models.PositiveIntegerField(default=0, verbose_name='شنوندگان ایران')),
                ('usa_listeners', models.PositiveIntegerField(default=0, verbose_name='شنوندگان آمریکا')),
                ('germany_listeners', models.PositiveIntegerField(default=0, verbose_name='شنوندگان آلمان')),
                ('uk_listeners', models.PositiveIntegerField(default=0, verbose_name='شنوندگان انگلستان')),
                ('canada_listeners', models.PositiveIntegerField(default=0, verbose_name='شنوندگان کانادا')),
                ('australia_listeners', models.PositiveIntegerField(default=0, verbose_name='شنوندگان استرالیا')),
                ('france_listeners', models.PositiveIntegerField(default=0, verbose_name='شنوندگان فرانسه')),
                ('other_countries_listeners', models.PositiveIntegerField(default=0, verbose_name='شنوندگان سایر کشورها')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='tracks.track')),
            ],
            options={
                'verbose_name': 'آمار ترک',
                'verbose_name_plural': 'آمار ترک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_streams', models.PositiveIntegerField(default=0, verbose_name='مجموع پخش\u200cها')),
                ('total_unique_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان منحصر')),
                ('total_playlist_saves', models.PositiveIntegerField(default=0, verbose_name='مجموع ذخیره در پلی\u200cلیست')),
                ('spotify_total_streams', models.PositiveIntegerField(default=0, verbose_name='مجموع پخش\u200cهای Spotify')),
                ('apple_music_total_streams', models.PositiveIntegerField(default=0, verbose_name='مجموع پخش\u200cهای Apple Music')),
                ('youtube_music_total_streams', models.PositiveIntegerField(default=0, verbose_name='مجموع پخش\u200cهای YouTube Music')),
                ('amazon_music_total_streams', models.PositiveIntegerField(default=0, verbose_name='مجموع پخش\u200cهای Amazon Music')),
                ('other_platforms_total_streams', models.PositiveIntegerField(default=0, verbose_name='مجموع پخش\u200cهای سایر پلتفرم\u200cها')),
                ('iran_total_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان ایران')),
                ('usa_total_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان آمریکا')),
                ('germany_total_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان آلمان')),
                ('uk_total_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان انگلستان')),
                ('canada_total_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان کانادا')),
                ('australia_total_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان استرالیا')),
                ('france_total_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان فرانسه')),
                ('other_countries_total_listeners', models.PositiveIntegerField(default=0, verbose_name='مجموع شنوندگان سایر کشورها')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آمار کاربر',
                'verbose_name_plural': 'آمار کاربران',
            },
        ),
        migrations.CreateModel(
            name='DailyStreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('streams', models.PositiveIntegerField(default=0, verbose_name='تعداد پخش')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streams', to='tracks.track')),
            ],
            options={
                'verbose_name': 'پخش روزانه',
                'verbose_name_plural': 'پخش\u200cهای روزانه',
                'unique_together': {('track', 'date')},
            },
        ),
    ]
